server:
  port: 9765

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false 
  mail:
    host: smtp.gmail.com
    port: 587
    username: choiyurim2@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          timeout: 50000
          starttls:
              enable: true             
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    
app:
  host: http://localhost:8080