server:
  port: 9777

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:postgresql://localhost:5432/testbook
    username: testuser
    password: testpass
  mail:
    host: smtp.gmail.com
    port: 587
    username: choiyurim2@gmail.com
    password: sjpiucrenqupyrtj
    properties:
      mail:
        smtp:
          auth: true
          timeout: 50000
          starttls:
              enable: true
              
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    
app:
  host: http://localhost:8080